name = "mysublink"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sublink-db" # <-- 请确保这是您在Cloudflare上创建的D1数据库的名称
database_id = "dc8ed9fd-7acc-4590-b731-7cc91347d470" # <-- 请务必将这里替换为您真实D1数据库的ID


